image: node:10

generate:
    script:
    - npm install hexo-cli -g --registry=https://registry.npmmirror.com
    - npm install --registry=https://registry.npmmirror.com
    - hexo clean
    - hexo generate
    
    after_script:
    - cd ./public
    - git init
    - git config user.name "${U_NAME}"
    - git config user.email "${U_EMAIL}"
    - git config http.proxy ${PROXY_URL}
    - git config https.proxy ${PROXY_URL}
    - git add .
    - git commit -m "Gitlab CI Auto Builder Docs at `date +"%Y-%m-%d %H:%M"`"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
