name: Deploy GitHub Pages
on: 
  push:
    branches:
      - master 

# 任务
jobs: 
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2

      # 生成静态文件
      - name: Build Pages
        run: |
          npm i hexo-cli -g 
          npm i 
          hexo g

      # 部署到 GitHub Pages
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repositoryName: xCss/driver.js
          branch: gh-pages
          folder: public
          commitMessage: GitHub Actions Auto Builder Docs at date +"%Y-%m-%d %H:%M"